### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by sophiapham** [Botnet-Honeypot/Honeypot#1]
## Description:
As a user I want to have a database design so that I know how the data will be structured.

## Tasks:
- [x] Design relational schema for IP addresses and login attempts and how they can be related to each other
- [x] Create a graphical database design
- [x] Design SQL schema

## Acceptance Criteria:
- [x] Is there a graphical database design that can be argued for?
- [x] Does the design use appropriate constraints and data types?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.

**Comment by Sannholm** [comment]
### First draft of logical database design
![ER](https://user-images.githubusercontent.com/999445/108997138-8c42d580-769f-11eb-989b-07a2c0432e50.png)

**Comment by Sannholm** [comment]
### Second draft of logical database design
![ER](https://user-images.githubusercontent.com/999445/109074047-7cef7680-76f7-11eb-8fc8-3216d445aab2.png)

**Comment by Sannholm** [comment]
### Final version of initial DB design
![ER](https://user-images.githubusercontent.com/999445/109391504-b69ec800-7917-11eb-9b6c-7264ad18c218.png)

**Comment by Sannholm** [comment]
### Revised (v2) of final version of initial DB design
![ER](https://user-images.githubusercontent.com/999445/109689554-b277e200-7b85-11eb-9051-11300a518413.png)
