### ISSUE TITLE
Configuration of Grafana

### ISSUE THREAD

**Issue by sophiapham** [Botnet-Honeypot/Honeypot#12]
## Description:
As an analyst, I want to be able to use Grafana to easier visualize the data from the database.
  
## Difficulty:
TBD

## Tasks:
- [ ] Connect Grafana to the database.
- [ ] Add useful queries and data visualizations.
- [ ] Design the layout of the dashboard to give a better overview of our data.

## Acceptance Criteria:
- [ ] Can Grafana read from the database?
- [ ] Is there a way to see a heatmap of attacker locations?
- [ ] Are there a way to see the most popular credentials?
- [ ] Are the queries and visualizations somewhat useful?
- [ ] Is there an appropriate representation for each type of data? (e.g. pie chart, word cloud)

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
