### ISSUE TITLE
Deployment of Grafana in Docker container

### ISSUE THREAD

**Issue by Sannholm** [Botnet-Honeypot/Honeypot#13]
## Description:
As a sysadmin I want Grafana to be deployed using a Docker container so that development, deployment and analysis can be performed consistently.
  
**Difficulty:** TBD

## Tasks:
- [ ] Find Docker image for Grafana.
- [ ] Set up docker-compose to be able to replicate and deploy.
- [ ] Choose & install plugins in the Docker container (https://grafana.com/grafana/plugins) e.g. Worldmap Panel

## Acceptance Criteria:
- [ ] Can the container be run locally?
- [ ] Can Grafana be connected to, using a browser?
- [ ] Are relevant and potentially useful plugins installed?

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
