### ISSUE TITLE
SSH Proxy

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#14]
## Description:
As a researcher I want attackers to connect to a target system so that the attacker can believe he is running commands locally, but really is not.

**Difficulty:** 13
## Tasks:
- [ ] Connect via SSH to target systems IP:Port where SSH is running in a container
- [ ] Take the data from the SSH connection between frontend and attacker and put it into the SSH connection between the frontend and the target system
- [ ] Take the data from the SSH connection between frontend and the target system and put it into the SSH connection between the frontend and attacker
- [ ] If the SSH connection on either side is terminated, then so is the other one.

## Acceptance Criteria:
- [ ] Anyone can SSH to the frontend which will proxy everything to the backend.
- [ ] SSH should behave as normal

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
