### ISSUE TITLE
Frontend backend integration

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#15]
## Description:
As a user  I want to the frontend to interact with the backend so that target systems can be obtained on demand

**Difficulty:** 8

## Tasks:
- [x] Make the frontend ask the backend API for IP:Ports to SSH into when a connection to a target system is needed
- [x] When the connection is terminated on either side (or after timeout?) tell the backend API to shutdown the target system

## Acceptance Criteria:
- [x] The frontend obtains target systems from the backend via an API
- [x] The frontend tells the backend when target systems are no longer needed
- [x] Is the server address of the backend configurable in the frontend?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
