### ISSUE TITLE
Deployment of backend docker containers

### ISSUE THREAD

**Issue by osksvan** [Botnet-Honeypot/Honeypot#16]
## Description:
As a sysadmin I want to have backend docker containers that the frontend software can connect to and execute commands on.

**Difficulty:** A Fibonacci number

## Tasks:
- [ ] Choose an image for the backend containers that will be executing commands.
- [ ] The image should have an SSH server that accepts connections.
- [ ] The image should look as much as possible as a real system.
- [ ] Set up docker-compose to be able to replicate and deploy.
- [ ] Install some common programs. (htop, place some web server files on the file system)

## Acceptance Criteria:
- [ ] A sysadmin can start up a container that accepts SSH connections.
- [ ] Should not easily be able to tell it is a docker container.
- [ ] Should be able to accept SSH connections.
- [ ] Should be able to execute commands sent over SSH.

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
