### ISSUE TITLE
SSH Proxy

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#17]
## Description:
As a researcher I want attackers to connect to a target system so that the attacker can believe he is running commands locally, but really is not.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Connect via SSH to target systems IP:Port where SSH is running in a container
- [x] Take the data from the SSH connection between frontend and attacker and put it into the SSH connection between the frontend and the target system
- [x] Take the data from the SSH connection between frontend and the target system and put it into the SSH connection between the frontend and attacker
- [x] If the SSH connection on either side is terminated, then so is the other one.

## Acceptance Criteria:
- [x] Anyone can SSH to the frontend which will proxy everything to the backend.
- [x] SSH should behave as normal

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
