### ISSUE TITLE
Control container for target containers

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#18]
## Description:
As a sysadmin I want to have a backend docker container that can run our custom backend software to start command execution containers.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Choose an image for the backend container that will be running the custom backend software.
- [x] Install Python 3.9 (Image only supports 3.8.8)
- [x] Install from requirements.txt
- [x] Set up docker-compose
- [x] Set up “docker in docker” (Socket solution) so that the backend software can control the Slav containers via Docker API.
- [x] Create interface that HTTP API can use to control containers

## Acceptance Criteria:
- [x] A sysadmin can start up a container that runs the backend software.
- [x] Should be able to control external docker containers (target containers) via Docker API.
- [x] Should be able to accept connections through HTTP-API (80)

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
