### ISSUE TITLE
Deployment of backend docker containers

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#19]
## Description:
As a sysadmin I want to have backend docker containers that the frontend software can connect to and execute commands on.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Choose an image for the backend containers that will be executing commands.
- [x] The image should have an SSH server that accepts connections.
- [x] The image should look as much as possible as a real system.
- [x] Install some common programs. (htop, place some web server files on the file system)
- [x] Python can start and stop containers
- [x] Each container has its own shared folder with host

## Acceptance Criteria:
- [x] A sysadmin can start up a container that accepts SSH connections.
- [x] Should not easily be able to tell it is a docker container.
- [x] Should be able to accept SSH connections.
- [x] Should be able to execute commands sent over SSH.
- [x] Each container has its own unique port
- [x] Possible to change the username and password for the SSH server

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
