### ISSUE TITLE
Python setup

### ISSUE THREAD

**Issue by sophiapham** [Botnet-Honeypot/Honeypot#2]
## Description:
As a programmer I want to have a ready Python developer environment so that I can start to develop my program.

## Tasks:
- [x] Setup venv (virtual environment) or similar for frontend and backend projects
- [x] Create file for dependency management (pyproject.toml, poetry)
- [x] Pick linter tool (runnable on command line, but also preferably with VSCode integration)
- [x] Setup shared linter config (under source control)
- [x] Decide docstring format to use
- [x] Setup Unit Testing
- [x] Setup System Testing
- [x] Setup Test Coverage Tool

## Acceptance Criteria:
- [x] Does the Python environment work similar for all members in the team?
- [x] Can project dependencies be installed without conflicting with other Python libraries already on the system?
- [x] Is there a way of automatically verifying that code follows a predefined, shared code style?
- [x] Is there a way to write and run automated unit tests?
- [x] Is there a way to write and run automated system tests?
- [x] Is there a way to see how much test coverage the project has?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
