### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#20]
## Description:
As a programmer I want to have CI for automatic tests and linter when I upload code to GitHub.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Run automated tests with reporting and coverage (pytest & Robot)
- [x] Run linter (pylint)
- [x] Run type checker (Pyright)
- [x] Decide if any tests should block pull requests from being accepted. If so, set it up.

## Acceptance Criteria:
- [x] Automated tests, linter and type checker run when someone uploads code to any branch.
- [x] Result of CI shows up in pull requests and commit history.

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).

**Comment by Bonzo1** [comment]
Not sure what labels/project boards fit with this issue.
