### ISSUE TITLE
Access permissions to Database

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#21]
## Description:
As a user, I want to make permission on the database, so that data cannot be overwritten by the wrong user.

**Difficulty:** A Fibonacci number

## Tasks:
- [ ] Set up another user (meant for frontend) for the database
- [ ] Give the user appropriate permissions so that it cannot overwrite existing data

## Acceptance Criteria:
- [ ] New user cannot alter previously existing DB information 

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
