### ISSUE TITLE
Send basic adversary information to Database

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#22]
## Description:
As a user, I want to be able to collect and store SSH usernames/passwords in a database, so that I can analyze the data later.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Write queries to insert session/connection information into DB
- [x] Write queries to insert login attempts (with username & password) into the DB
- [x] Write queries to insert other attacker actions into the DB
- [x] Implement queries in `frontend.logging` module

## Acceptance Criteria:
- [x] Session/connection information is stored in the database
- [x] Usernames & passwords stored in the database

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
