### ISSUE TITLE
Frontend connects to DB

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#23]
## Description:
As a user, I want to be able to connect to a database, so that I will be able to store data.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Pick library to communicate with the DB (maintained library)
- [x] Connect to the DB through SSL
- [x] Log in to the DB
- [x] Send (any?)data to the DB

## Acceptance Criteria:
- [x] Can a connection be made to the database from the frontend?
- [x] Can the desired data be inserted into the DB?
- [x] Is the DB address configurable?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
