### ISSUE TITLE
Basic SSH connection info collection

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#25]
## Description:
As a security researcher I want to be able to collect SSH connection information so that I later can analyze the data.

**Difficulty:** 8

## Tasks:
- [x] Collect the connection data including connection data, login credentials tried and timestamp.
- [x] Design interface for logging module. (Benjamin & Sophia) https://github.com/Botnet-Honeypot/Honeypot/pull/29
- [x] Send to logging module (Log to console for now)

## Acceptance Criteria:
- [x] The server should be able to handle multiple connections
- [x] Is it possible to collect connection data, like login credentials tried and timestamp?
- [x] Is it possible for the collected information to be sent to the logging module (console for now)?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
