### ISSUE TITLE
Deploy frontend and database

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#28]
## Description:
As a researcher I want my frontend and database deployed so that I can use it

**Difficulty:** A Fibonacci number
13
## Tasks:
- [x] Figure out how to deploy docker container on Azure
- [x] Update dockerfile for frontend
- [x] Deploy docker container
- [x] Set up database
- [x] Database data have to be stored in a permanent manner

## Acceptance Criteria:
- [x] Frontend and database can talk with each other
- [x] Frontend have a public IP and port 22 is open
- [x] Database have a public IP and have an open port

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is documented (sphinx docstring).
