### ISSUE TITLE
Deployment of database

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#3]
As a user I want to deploy a database, so that it can start to collect data.

## Tasks:
- [x] Make the DB up and running
- [x] Set up basic (login attempts) tables in DB
- [x] Write to tables
- [x] Read from tables

## Acceptance Criteria:
- [x] The DB is able to run and you can read and write to DB
- [x] Can the database be run locally?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
