### ISSUE TITLE
Cleanup code in SSHServer

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#36]
## Description:
As a developer I want to the code to be nice so that it easier to develop with
**Difficulty:** 8

## Tasks:
- [x] #35 Needs to be merged before this can be started
- [ ] Stop passing around so many instance variables from ConnectionManager -> ConnectionHandler -> Server _https://github.com/Botnet-Honeypot/Honeypot/pull/35#discussion_r587900677_ _https://github.com/Botnet-Honeypot/Honeypot/pull/35#discussion_r587904111_
  - Read settings from config file into singleton that can be used everywhere?
  - Read settings from environment variables as fallback since it's probably easier to configure the Docker containers with?
  - This config thing should probably be its own user story alone
- [x] Don't use `print()` statements, use logging for everything
- [x] Create a ssh subdirectory under protocols and move the classes inside ssh.py to different files there?
- [ ] Use coroutines for ConnectionHandler instead? _https://github.com/Botnet-Honeypot/Honeypot/pull/35#discussion_r587903699_
- [x] Just fix all todos in ssh.py
- [x] _https://github.com/Botnet-Honeypot/Honeypot/pull/35#discussion_r593119766_
- [x] _https://github.com/Botnet-Honeypot/Honeypot/pull/35#discussion_r593121948_

## Acceptance Criteria:
- [x] Code still works
- [x] Tests still work

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
