### ISSUE TITLE
Make SSH Server good

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#37]
## Description:
As a user I want the SSH server to follow the SSH standard so that it acts as a normal SSH server

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Allow people who connect to the SSH server to open only one channel of type "session"
- [x] Don't drop the user in the "interactive part of SSH" before they send a "[shell request](https://tools.ietf.org/html/rfc4254#page-13)"
- [x] Handle "[exec](https://tools.ietf.org/html/rfc4254#page-13)" requests
- [x] Only allow a single "exec" request or a single "[shell request](https://tools.ietf.org/html/rfc4254#page-13)"
- [x] Change Paramiko banner thing that you get if you nmap the frontend with version detection to a generic one such as "OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)"

## Acceptance Criteria:
- [x] Users can fail establishing a channel x times before they request the "session" channel
- [x] When they have requested the above channel, all other channel requests will be denied
- [x] exec, and shell requests are handled appropriately

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).

**Comment by klondi** [comment]
If you are targeting IOT go for a dropbear banner, for example: "SSH-2.0-dropbear"
