### ISSUE TITLE
Frontend-backend communication (HTTP API)

### ISSUE THREAD

**Issue by Sannholm** [Botnet-Honeypot/Honeypot#39]
## Description:
As a developer I would like to be able to connect the frontend and the backend over the network using a well-defined interface so I can control target systems and collect information.

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Research appropriate way to define an HTTP API (e.g. REST, GraphQL, generate client and server from DSL, gRPC, Protobuf)
- [x] Find library for running an HTTPS server (with support for JSON requests and responses, if applicable)
- [x] Design API "start" endpoint (and its JSON schema, if applicable)
- [x] Design API "stop" endpoint (and its JSON schema, if applicable)
- [x] Implement "start" endpoint to start container
- [x] Implement "stop" endpoint to stop container and collect information
- [x] Design and implement frontend module wrapping the HTTP API

## Acceptance Criteria:
- [x] Does the HTTP API follow a typical REST design or similar?
- [x] Is there an endpoint for requesting a target system to be started?
- [x] Does the API return a unique ID for the target system after starting it?
- [x] Is there an endpoint for requesting a target system to be stopped?
- [x] Is the API able to return information about the target system after it has been stopped?
- [x] Can the information about the target system be extended in the future?
- [x] Do the endpoints connect to and use the backend module for controlling containers?
- [x] Is there a nice client interface on the frontend for starting and stopping target systems that abstracts away the HTTP communication?
- [x] Is the HTTP server interface and port configurable?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
