### ISSUE TITLE
Docker configuration

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#4]
As a programmer I want to execute the frontend in a docker container.

## Tasks
- [x] Create a Dockerfile/Docker compose file for frontend and backend projects

## Acceptance Criteria
- [x] Does the Dockerfile install Python 3.9?
- [x] Does the Dockerfile copy over the source files?
- [x] Does the Dockerfile install all pip dependencies?
- [x] Does the Dockerfile run the software?
- [x] Does the Dockerfile set up the ports correctly?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
