### ISSUE TITLE
Log commands

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#41]
## Description:
As a developer I would like to be able to log the commands an attacker  uses after logging in to our honeypot. (High)

**Difficulty:** 13

## Tasks:
- [x] Identify commands
- [x] Send command to database

## Acceptance Criteria:
- [x] Commands an attacker uses will be logged in our database

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
