### ISSUE TITLE
Log network traffic

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#42]
## Description:
As a developer I would like to be able to log the network traffic an attacker  uses after logging in to our honeypot. (Low)

**Difficulty:** 13

## Tasks:
- [x] Logg the attackers network traffic
- [ ] Send the logg to our database

## Acceptance Criteria:
- [ ] When network traffic is looged in the database

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
