### ISSUE TITLE
Log files being changed

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#43]
## Description:
As a developer I would like to be able to log the files being changed when an attacker is logged in to our honeypot. (Low)

**Difficulty:** A Fibonacci number

## Tasks:
- [ ] Identifiy files being changed
- [ ] Send information about the changed files to our database

## Acceptance Criteria:
- [ ] When changed files is identified and sent to our database

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
