### ISSUE TITLE
Log downloaded files

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#44]
## Description:
As a developer I would like to be able to log the files an attacker downloads after logging in to our honeypot.

**Difficulty:** 13

## Tasks:
- [x] Research best method to achieve this
- [x] Make proof of concept
- [x] Make backend capture traffic from a specific container
- [x] Extract downloaded files over HTTP
- [ ] Decrypt HTTPS
- [x] Send files and metadata back to frontend
- [x] Make frontend store files and metadata in database

## Acceptance Criteria:
- [x] Can downloads through HTTP(S) be captured?
- [ ] Can downloads over HTTPS be decrypted?
- [x] Is Source IP, URL, contents, and filetype of the download saved to the database?

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).
