### ISSUE TITLE
Make it possible to handle several channels at once

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#45]
## Description:
As a user I want to the user to be able to open multiple channels so that more data can be received

**Difficulty:** 13

## Tasks:
- [x] Make it possible for people connecting to the honeypot to open several channels
- [x] Only one shell request or exec request can succeed per channel

## Acceptance Criteria:
- [x] It is possible to open multiple channels
- [x] Only one shell request or exec request succeeds per channel

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
