### ISSUE TITLE
HTTP API integration with backend control container

### ISSUE THREAD

**Issue by Bonzo1** [Botnet-Honeypot/Honeypot#48]
## Description:
As a developer I want to integrate the HTTP API with the backend control container so that connections from the frontend can recieve a container

**Difficulty:** A Fibonacci number

## Tasks:
- [ ] Read documentation about the API
- [ ] Recieve connections from frontend
- [ ] Respond to connections from frontend
- [ ] Interpret and act on requests
- [ ] Make connections recieve a new container

## Acceptance Criteria:
- [ ] Able to give containers to frontend connections
- [ ] Able to stop/destroy containers as per HTTP API requests

## Definition of Done:
- [ ] All Acceptance Criteria of the user story are met
- [ ] Code meets our Coding Standards.
- [ ] Code is committed into GitHub.
- [ ] Functional tests are performed. 
- [ ] Code review is conducted by the majority of the group.
- [ ] The code is covered by a minimum of 70% Unit Tests.
- [ ] The code is documented (sphinx docstring).

**Comment by Bonzo1** [comment]
Blocked until [HTTP API #39](https://github.com/Botnet-Honeypot/Honeypot/issues/39) specification is done
