### ISSUE TITLE
Log SSH channel output

### ISSUE THREAD

**Issue by Sannholm** [Botnet-Honeypot/Honeypot#49]
## Description:
As a developer I would like to be able to log the full output of an SSH session.

## Tasks:
- [x] Collect raw SSH channel output as bytes
- [x] Send SSH channel output to frontend logging module

## Acceptance Criteria:
- [x] SSH channel output is logged in the database
- [x] Each channel's output is logged with a unique channel id

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).

**Comment by Sannholm** [comment]
Depends on pull request #46
