### ISSUE TITLE
Improve the shell session experience

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#54]
## Description:
As a user I want to do X so that I can Y

**Difficulty:** 8

## Tasks:
- [x] #52 Has to be merged before
- [x] Collect all shell session data in some kind of buffer and associate data with a timestamp
- [x] After the shell session ends insert the data

The interesting methods to change are `proxy_data` in `_proxy_handler.py` and a new `insert_new_event` in `_postgres.py`

## Acceptance Criteria:
- [x] It doesn't lag when opening a shell session (Data does no longer have to make the trip Attacker -> Frontend -> Database -> Backend)
- [x] The data makes does the (Attacker -> Frontend -> Backend) trip during an interactive shell session

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
