### ISSUE TITLE
Fix shell session delay

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#55]
## Description:
As a user I want to do X so that I can Y

**Difficulty:** A Fibonacci number

## Tasks:
- [x] #52 Has to be merged
- [x] Fix the 0.1 seconds delay in `proxy_data` [Suggestion](https://docs.python.org/3/library/select.html) with the [fileno()](http://docs.paramiko.org/en/stable/api/channel.html?highlight=channel#paramiko.channel.Channel.fileno) method. (Might only work on unix not sure)

## Acceptance Criteria:
- [x] There is not a 100ms sleep anymore (at least not for unix)

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
