### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by ALX99** [Botnet-Honeypot/Honeypot#57]
## Description:
As a user I want to do X so that I can Y

**Difficulty:** A Fibonacci number

## Tasks:
- [x] Log new events associated with ssh
- [x] Associate SSH session with SSH remote version string (when beginning an SSH session we can provide their remote version)

## Events

- Env request (chanid: INT, name: STR, value: STR)
- Tcpip request (chanid: INT, origin: STR, origin_port: INT, destination: STR, destination_port: INT)
- x11 request (chanid: INT, single_connection: BOOL, auth_protocol: STR, auth_cookie: BYTES, screen_number: INT)
- forward agent request (chanid: INT)
- port forward request (address: STR, port: INT)

We don't utilize the chanid in other place so idk if it matters if we save it, on the other hand saving it won't hurt I guess

## Acceptance Criteria:
- [x] Data can be inserted into the database
- [x] The data can be logged by the console logger as well as the postgres logger

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
