### ISSUE TITLE
SSH connection

### ISSUE THREAD

**Issue by tvigg** [Botnet-Honeypot/Honeypot#9]
## Description:
As a security researcher I want to accept SSH connections from attackers so that they are able to get access to the system that I want them to probe.

**Difficulty:** 8

## Tasks:
- [x] Choose what library to use
- [x] Accept a connection 
- [x] Make it possible to send response(s) (“Welcome, you’re in”, command results)
- [x] Receive commands

## Acceptance Criteria:
- [x] Is it possible to connect to the system via SSH?
- [x] Does the system print the connection status in the console?

## Definition of Done:
- [x] All Acceptance Criteria of the user story are met
- [x] Code meets our Coding Standards.
- [x] Code is committed into GitHub.
- [x] Functional tests are performed. 
- [x] Code review is conducted by the majority of the group.
- [x] The code is covered by a minimum of 70% Unit Tests.
- [x] The code is documented (sphinx docstring).
